<a href="https://colab.research.google.com/github/mauricio5521/data-science/blob/Alura/inmuebles_cdmx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas**

#**Importando la Base de Datos**

In [6]:
import pandas as pd

url = "https://gist.githubusercontent.com/ahcamachod/a572cfcc2527046db93101f88011b26e/raw/ffb13f45a79d31223e645611a119397dd127ee3c/alquiler.csv"

pd.read_csv(url)

      Tipo;Colonia;Habitaciones;Garages;Suites;Area;Valor;Condominio;Impuesto
0          Cocineta;Condesa;1;0;0;40;5950.0;1750.0;210.0
1                       Casa;Polanco;2;0;1;100;24500.0;;
2      Conjunto Comercial/Sala;Santa Fe;0;4;0;150;182...
3      Departamento;Centro Histórico;1;0;0;15;2800.0;...
4          Departamento;Del Valle;1;0;0;48;2800.0;805.0;
...                                                  ...
25116  Cochera/Estacionamiento;Centro Histórico;0;0;0...
25117  Cocineta;Centro Histórico;0;0;0;27;2800.0;1225...
25118  Departamento;Mixcoac;2;1;0;48;4900.0;1781.5;129.5
25119  Departamento;Lomas de Chapultepec;2;0;0;70;105...
25120  Conjunto Comercial/Sala;Centro Histórico;0;0;0...

[25121 rows x 1 columns]

In [8]:
datos = pd.read_csv(url, sep=';')
datos

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN
...,...,...,...,...,...,...,...,...,...
25116,Cochera/Estacionamiento,Centro Histórico,0,0,0,755,49000.0,NaN,NaN
25117,Cocineta,Centro Histórico,0,0,0,27,2800.0,1225.0,87.5
25118,Departamento,Mixcoac,2,1,0,48,4900.0,1781.5,129.5
25119,Departamento,Lomas de Chapultepec,2,0,0,70,10500.0,2660.0,NaN
25120,Conjunto Comercial/Sala,Centro Histórico,0,0,0,250,22750.0,14721.0,3881.5

In [12]:
datos.head(10)

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN
5,Casa de Condominio,Santa Fe,5,4,5,750,77000.0,NaN,NaN
6,Conjunto Comercial/Sala,Centro Histórico,0,3,0,695,122500.0,67175.5,10605.0
7,Departamento,Centro Histórico,1,0,0,36,4200.0,NaN,NaN
8,Departamento,Condesa,1,0,1,40,7000.0,1963.5,175.0
9,Cocineta,Condesa,1,0,0,27,6300.0,1753.5,NaN

In [13]:
datos.sample(10)

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
15992,Departamento,Lomas de Chapultepec,3,3,2,240,70000.0,12250.0,2530.5
13629,Departamento,Coyoacán,2,1,2,85,35000.0,13650.0,1050.0
14069,Departamento,Santa Fe,2,1,1,80,8750.0,4945.5,NaN
6610,Departamento,Coyoacán,3,2,2,163,19250.0,8400.0,2275.0
2978,Conjunto Comercial/Sala,Santa Fe,0,1,0,22,3500.0,1750.0,NaN
15022,Departamento,Lomas de Chapultepec,4,3,3,509,87500.0,16870.0,8260.0
1292,Conjunto Comercial/Sala,Santa Fe,0,0,0,60,6300.0,4620.0,1610.0
9234,Departamento,Santa Fe,4,2,2,146,17150.0,6300.0,11550.0
7592,Conjunto Comercial/Sala,Centro Histórico,0,0,0,423,38500.0,30873.5,8144.5
12539,Departamento,Narvarte,2,0,0,61,4200.0,1750.0,NaN

In [16]:
type(datos)

pandas.core.frame.DataFrame

NameError: name 'read_csv' is not defined